version: "3"

services:
  backend:
    network_mode: bridge
    build:
      context: .
      dockerfile: build/backend.dockerfile
    ports:
      - "8082:8082"
      - "19901:19000"
  frontend:
    network_mode: bridge
    build:
      context: .
      dockerfile: build/frontend.dockerfile
    ports:
      - "4200:4200"
    restart: unless-stopped
